### ISSUE TITLE
Label "Waiting for author" is not removed when the author has answered 

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/issuebot#114]
On repo PrestaShop/PrestaShop, QA team manages the issues.
We add  _NMI_ and _Waiting for author_ labels when issue needs more details from the author.

When the author answers, issuebot should automatically delete the _Waiting for author_ label for more clarity.

But I have noticed that lately, issuebot does not remove the label.
Example : https://github.com/PrestaShop/PrestaShop/issues/33449

**Comment by kpodemski** [comment]
Another example:
https://github.com/PrestaShop/PrestaShop/issues/33477

**Comment by boherm** [comment]
Are we totally sure that the issuebot is actually running? 😅
(cc @matks!)

**Comment by boherm** [comment]
Ok! @elodie-bil3 have restarted the bot and It seems to work properly now.
(For informations, the bot didn't work since july 21th.)
