### ISSUE TITLE
Topwatcher label is not applied automatically

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/issuebot#30]
Issuebot should flag automatically issues as "Topwatcher" when the issue reaches more than 5 participants
cf 
https://github.com/PrestaShop/PrestaShop/issues/14703
https://github.com/PrestaShop/PrestaShop/issues/9599

**Comment by hibatallahAouadni** [comment]
Hello @MatShir 

I think this issue has been fixed :tada: check these issues:
https://github.com/PrestaShop/PrestaShop/issues/16952#issuecomment-1105707075
https://github.com/PrestaShop/PrestaShop/issues/26754#issuecomment-1152935544

But we have another issue, the issuebot flag automatically the **CLOSED** issues as `Topwatcher` when the issue reaches more than 5 participants (see the issue #78 )

So could you please close the issue as Fixed :wink: 

Thanks!
