### ISSUE TITLE
Label NeedsSpecs is not removed when we close the issue

### ISSUE THREAD

**Issue by hibatallahAouadni** [PrestaShop/issuebot#33]
### Describe the bug
When we close the issue by merging a PR or the contributor just close the issue, the issue-bot doesn't remove the `NeedsSpecs` label.
Check this [link](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3A%22Needs+specs%22+is%3Aclosed), we already have 16 closed issues with `NeedsSpecs` label :disappointed: 

### Expected behavior
The issue-bot delete the `NeedsSpecs` label when the issue is closed

### Steps to reproduce

1. Create a new issue
2. Add the label `NeedsSpecs` to this issue
3. Then close it
4. See error > the label `NeedsSpecs` is not removed

### Screenshots
![image](https://user-images.githubusercontent.com/23308427/149553488-43ae1bcc-5955-4044-8b49-fbe132a212d4.png)

---
![image](https://user-images.githubusercontent.com/23308427/149553466-34f4bcaf-2ac3-4d47-b7d6-dac5fc4aca74.png)

**Comment by matthieu-rolland** [comment]
at first I didn't understand why it worked on my kanban and not on Prestashop's kanban:

Label `Needs Specs` was badly written (`Needs specs`) in GitHub, just had to rename it 👍
