### ISSUE TITLE
Project Management between Kanban

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/issuebot#82]
It is hard to keep updating our private and public kanban.

When I add a ticket to a public kanban (ex:Kanban 1.7.8.8), it is added automatically to the MaxiKanban with the right status.

When I remove a ticket from the Maxi Kanban, the ticket is kept in the public kanban without change its column.

**Comment by eshraw** [comment]
Contact @NeOMakinG or @matthieu-rolland for more details.
